### ISSUE TITLE
PRIORITY: Translation interface is broken on sndcomp:  gives Parse error: syntax error, unexpected '[' in /srv/lingweb/www/sndcomp/admin/query/translationClass.php on line 419

### ISSUE THREAD

**Issue by PaulHeggarty** [sndcomp/website#100]

**Comment by runjak** [comment]
This was just fixed in c4e1b0dc9e5b424cc0ba5b4374a3ee6cc7cba43c - I've sent a Mail to @Bibiko so that the Patch can be rolled out. The problem arose from an older PHP version running on the MPI Server, that doesn't provide a lot of the usual syntax that I expected. Because I have a far newer version of PHP running on my development machine, I sadly didn't discover this problem during development.

**Comment by Bibiko** [comment]
> On 23 Mar 2015, at 12:58, Jakob Runge <notifications@github.com> wrote:
> 
> This was just fixed in c4e1b0d - I've sent a Mail to @Bibiko so that the Patch can be rolled out. The problem arose from an older PHP version running on the MPI Server, that doesn't provide a lot of the usual syntax that I expected. Because I have a far newer version of PHP running on my development machine, I sadly didn't discover this problem during development.

Done.

******************************************************
Hans-Joerg Bibiko
Max Planck Institute for Evolutionary Anthropology
Department of Linguistics
Deutscher Platz 6	phone:	+49 (0) 341 3550 341
D-04103 Leipzig		fax:	+49 (0) 341 3550 333
Germany			e-mail:	bibiko [at] eva.mpg.de
******************************************************

**Comment by LauraWae** [comment]
great

2015-03-23 14:41 GMT+01:00, Hans-J�rg Bibiko <notifications@github.com>:
>
