### ISSUE TITLE
Hovering over a contributor's name flashes up an underlined paragraph sign

### ISSUE THREAD

**Issue by PaulHeggarty** [sndcomp/website#116]

**Comment by runjak** [comment]
Instead of the paragraph we want a chain-like link icon, and it would be good if highlighting of contributors was changed so that the entry is not at the top of the page, but ca. 5em down, and the background color is changed to something greenish (see Flemish-Dutch-Frisian / color 4). It also appears that highlighting sometimes doesn't work correctly when the page is just being loaded.

**Comment by runjak** [comment]
I've tested it, and found out that I couldn't reproduce the problems with initial loading I expected to see,
and mentioned in 515e11d2e1f7cbbc81b5416d06498f49c1f9da06. Since everything else is more or less place, I consider this issue solved for now.
