### ISSUE TITLE
The contributor photo for Scott Sadowsky is not working.  I changed it recently, and that includes a change of format from jpg to png, I think.  But that shouldn't stop it working, presumably?

### ISSUE THREAD

**Issue by PaulHeggarty** [sndcomp/website#127]

**Comment by runjak** [comment]
This appears to be a problem for multiple contributors on the server at the moment.
I remember that there were problems with an update because some of the pictures weren't originally tracked with git, but have instead been added to the server directly.
This is a problem I didn't think of when closing #46.
I'll make sure to fix this in git and afterwards get correct the pictures on the server.

**Comment by runjak** [comment]
This issue is closed because of e50b6f91dc51549e6210781bb6d1c2ee1d9fedec.
