### ISSUE TITLE
TranslateStatic:FixMe!  is appearing all over the sndcomp site again.  Even in English.

### ISSUE THREAD

**Issue by PaulHeggarty** [sndcomp/website#142]

**Comment by runjak** [comment]
Memo for myself: this is supposedly the same as #110.

**Comment by runjak** [comment]
Ok, I think I can reconstruct part of this issue now.
When a translation doesn't get fetched correctly, but some data is saved in sessionStorage,
the site would use that data instead of trying to fetch it again.
To fix this I will turn off the sessionStorage feature and see if this hurts performance more than expected/wanted. If the impact on performance is higher than wanted, I'll instead try to implement some validation for the data already held.

**Comment by runjak** [comment]
Since we do some server side caching anyway, it would be possible to use [AppCache](http://www.html5rocks.com/en/tutorials/appcache/beginner/) in the long run to increase performance if we want to. That way we could also introduce client side caching without {Data,Translation}Storage being aware of it.
