### ISSUE TITLE
PRIORITY:  I'd like it to work if I type the URl http://lingweb.eva.mpg.de/sndcomp/#/Romance/, but apparently the site ignores that and still goes to Germanic.

### ISSUE THREAD

**Issue by PaulHeggarty** [sndcomp/website#73]

**Comment by runjak** [comment]
To solve this issue I'll extend the shortlink feature #8 so that, in cases where a keyword like 'Romance' doesn't match a defined shortlink, it will try to match it with a study. This would still leave the possibility open to create a shortlink for the name of a study to direct a client to a special page if that is preffered. Until this feature is implemented, it is also already possible, to make use of the shortlink feature as a workaround.
