### ISSUE TITLE
PRIORITY:  MAP view is broken?  It only ever loads the top-left (NW) corner map cell.  The others never seem to load.

### ISSUE THREAD

**Issue by PaulHeggarty** [sndcomp/website#75]

**Comment by runjak** [comment]
I'll look if this problem reappears.

**Comment by runjak** [comment]
Could reproduce this in firefox, when switching between several views.

**Comment by runjak** [comment]
It appears that changing the size of the browser window triggers a redraw of the map.
Maybe this issue has something to do with WdsxLgs view breaking the layout of the content area,
or the Map picking up incorrect size information otherwise.
As a workaround I could make sure to check the correct size of the map everytime the Map is opened.
