### ISSUE TITLE
Cant access to Study group "englishes": if i select it in the group selector in the upper left corner of the site, it only shows the Germanic ones

### ISSUE THREAD

**Issue by LauraWae** [sndcomp/website#97]

**Comment by runjak** [comment]
Indeed, this appears to be broken…

**Comment by runjak** [comment]
OK - so I can reproduce this on the lingweb server, but not on my local setup. So I figured I'd follow the query JavaScript does when it tries to fetch 'Englishes', and see what happens.
It turns out that 'query/data?study=Englishes' produces a Fatal error, stopping the script,
and that the page falls back on the data it already has.
![fatal](https://cloud.githubusercontent.com/assets/5417642/6845240/a2dbc5e0-d3b2-11e4-962f-150800edb010.png)
It appears that fetching 'Englishes' uses more memory than the server is configured to provide to PHP, and that this stops the script. What I will do is the following:
1: Provide clients with a message saying that loading the study group failed so that they know what happened.
2: See what ways I can find to fix this case. Possible solutions include:
  * Check if it would help to generate study cases directly after import.
    This would also reduce loading times for clients as they could just start fetching data without the server generating it on the fly.
  * See if some part of the code eats all the memory and can be improved
  * See if we can adjust the server setup

**Comment by runjak** [comment]
Note that the actual size of the generated JSON output is currently about 6323452, and thus about 10 times lower than the overall resource consumption in that case.
