### ISSUE TITLE
Polish cognate "thunder": there is one unnecessary small bracket at the right hand side of the transcription brackets

### ISSUE THREAD

**Issue by LauraWae** [sndcomp/website#99]
![bracket](https://cloud.githubusercontent.com/assets/10007762/6776476/462e2b32-d13f-11e4-8571-3b98c87d68d0.PNG)

**Comment by runjak** [comment]
Whats happening here is this: The site tries to display a superscript for that transcription, but due to buggy code from me it fails to do so. Instead it converts it's data to a string starting with '[object', and uses the first element as superscript, and the 'o' as a tooltip. I should be able to fix this soon.
